version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run:
          name: "Run Pylint"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install pylint
            pylint tap_salesforce -d missing-docstring,invalid-name,line-too-long,too-many-locals,too-few-public-methods,fixme
  test:
    docker:
      - image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run: 'echo "Hello"'
